# Generated by Django 2.0.7 on 2018-07-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='gallery_image',
        ),
    ]
