# Generated by Django 2.0.7 on 2018-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180711_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='cover_image_name',
        ),
    ]
