# Generated by Django 2.0.7 on 2018-08-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180802_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_cover',
            field=models.ImageField(default='images/no-image.jpg', upload_to='images'),
        ),
    ]
